// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: makered.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const makeRed = `-- name: MakeRed :execrows
UPDATE users
SET is_chirpy_red = true
WHERE id = $1
`

func (q *Queries) MakeRed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, makeRed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
